### PR TITLE
Allowing image offset to be specified in config.toml (fixes issue #48)

### LINKED ISSUE #48: Add a way to specify an offset in config.toml
I would like to use launchpad for the micropython project with a custom config.toml file. Hovewer, for esp32s3 I need to use 0x0 offset. As I see there is no way to specify the offset for the binary in the config.toml, only using `DIY` mode.

### PR DESCRIPTION
**Pull request by vanniaz**
## Description

Modified function `downloadAndFlash` to handle image offset.
Image offset should be added to config.toml inside the section of the corresponding app. If offset is not specified it defaults to zero.
Also, added an alert if the image file is not found, because otherwise there is no warning to the user (but this should also be handled outside this function, to disable the flashing complete message).

## Related

Fixes #48 (Add a way to specify an offset in config.toml)

Example of (partial) config.toml, with offset 0x10000:

```
# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["example_app"]

...

[example_app]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3", "ESP32-S3"]
# Starting address for firmware flashing
offset = "0x10000"
# Configure the name of the binary file
image.esp32 = "example.bin"

```

## TBD

Remove alert when image file not found, and handle it outside this function.

### CODE REVIEW

File: js/index.js [hunk 1]
```diff
@@ -675,20 +675,28 @@ programButton.onclick = async () => {
...
 
 async function downloadAndFlash(fileURL) {
-    let data = await utilities.getImageData(fileURL);
+	let data = await utilities.getImageData(fileURL);
+	let strOffset = config[deviceTypeSelect.value].offset;
+	let offset = 0x0000;
+	if ( strOffset !== undefined )
+	{
+	    offset = parseInt(strOffset);
+	}
```
Comment (RushikeshPatange) [inline js/index.js:684]: Could we simplify this logic using the nullish coalescing operator?
```suggestion
	let offset = parseInt(config[deviceTypeSelect.value].offset ?? "0x0000");
```

Comment (RushikeshPatange) [inline js/index.js:684]: Seeing one tab extra before each line in newly added code as formatting changes,
Can you please revert them and match the formatting that align with the existing.

File: js/index.js [hunk 2]
```diff
@@ -675,20 +675,28 @@ programButton.onclick = async () => {
...
                 flashMode: undefined,
                 flashFreq: undefined,
                 eraseAll: false,
                 compress: true,
             };
             await esploader.writeFlash(flashOptions);
-        }
+        } else {
+	    alert("Image file not found");
+	}
```
Comment (RushikeshPatange) [inline js/index.js:699]: Thanks for adding this!

We're working on improving error handling, so we might want to handle such alerts in a more structured way with a better UI/UX experience. For now, we can keep this, but in the future, we might refine this logic.

**Review by RushikeshPatange — CHANGES_REQUESTED** [review]

**Comment by vanniaz** [comment]
Hi, I confess that I had no idea about what a _nullish coalescing operator_ was! My knowledge of Javascript is elementary school level... However I looked it up and it is simpler than it sounds, so I will try to simplify this logic.
You are right about the extra tabs, I just copied and pasted offline code to the online editor and probably the tab spacing is not handled well, I will re-edit it.
The alert is more to be intended as a reminder to improve error handling than a real solution (perhaps we could already let this function return a boolean value, which could be used in the future for better error handling, what do you think?)

File: js/index.js [hunk 3]
```diff
@@ -675,20 +675,23 @@ programButton.onclick = async () => {
 }
 
 async function downloadAndFlash(fileURL) {
-    let data = await utilities.getImageData(fileURL);
+	let data = await utilities.getImageData(fileURL);
+	let offset = parseInt(config[deviceTypeSelect.value].offset ?? "0x0000");
```
Comment (RushikeshPatange) [inline js/index.js:679]: Still the extra tab changes are visible( need onlye one tab from the start of line here are two)
The both lines start should align with try start
If you are editing the code directly on github code editor, please try to do it manually to one tab only which fullfill above expected formatting

**Review by RushikeshPatange — CHANGES_REQUESTED** [review]
Once you've made the requested changes, could you squash all commits into a single commit with clear description ? 
It would be great to have a commit message that clearly describes the improvements in this PR and provides some context on the enhancements made. 
Thanks!

**Comment by vanniaz** [comment]
> Once you've made the requested changes, could you squash all commits into a single commit with clear description ? It would be great to have a commit message that clearly describes the improvements in this PR and provides some context on the enhancements made. Also mark all the requested changes resolved after completion Thanks!

Well, you are probably overestimating my knowledge of GIT!
I'll try, let's see what I can do...
Thanks!

**Comment by vanniaz** [comment]
I did the squash (not sure if I did it correctly).
However I still see differences in blank lines, I am trying to fix them then I will squash the commits again (sorry for beginner's inexperience!)

**Comment by vanniaz** [comment]
I still see a difference in a blank line at the end of the file, probably my fault in interpreting the diff, apart from this now the commits have been squashed into a single one, so I think it could be merged.

**Comment by RushikeshPatange** [comment]
Hey @vanniaz,

Your changes look good to go for merge! 
Could you please update the commit message to be a one-to-two-liner while still being descriptive?

Something like:
Enhance downloadAndFlash to support flashing at a configurable offset rather than a fixed default one. Also, add an alert for missing image file.

Also, please resolve any pending requested changes by replying to them, mentioning if they have been addressed in the latest commit.

**Comment by vanniaz** [comment]
@RushikeshPatange I amended the commit to change the message, please check if it is ok. Also, there should be no more unresolved pending requested changes. But again I have no experience with GIT so I am not sure I did everything correctly.
Just one note about the confgurable offset: I tested it with my own firmware and it works, perhaps it would need a more extensive testing with multiple apps etc. (but I have not enough spare time to do any more tests)
